/**
 * Downloads the three families the design uses from Google Fonts and writes
 * them into `public/fonts/` with a local `fonts.css`.
 *
 * Self-hosting rather than linking to fonts.googleapis.com is deliberate: the
 * app is single-user and offline-first, so a cold start should not have to talk
 * to a third party before it can render.
 *
 * Run with `node scripts/fetch-fonts.mjs`. Only needed when the font stack
 * changes — the generated files are committed.
 */
import { createHash } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "public/fonts");

// Matches the <link> in the original design prototype (project/Nightly.dc.html).
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;0,6..72,500;1,6..72,300" +
  "&family=Instrument+Sans:wght@400;500;600" +
  "&family=IBM+Plex+Mono:wght@400;500&display=swap";

// A browser UA is required to get woff2 (and the variable-font builds) back.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// English-first app; latin + latin-ext covers everything realistically typed
// into it while keeping the payload to a handful of files.
const KEEP_SUBSETS = ["latin", "latin-ext"];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function main() {
  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

  // Google's CSS annotates each block with a `/* latin */`-style subset comment.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error("Could not parse any @font-face blocks");

  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  const out = [];
  // Newsreader and Instrument Sans are variable fonts, so Google hands back the
  // same file for every weight we asked for. Store each distinct file once.
  const byHash = new Map();

  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.includes(subset)) continue;

    const pick = (prop) => (block.match(new RegExp(`${prop}:\\s*([^;]+);`)) || [])[1]?.trim();
    const family = pick("font-family").replace(/['"]/g, "");
    const style = pick("font-style") || "normal";
    const weight = pick("font-weight") || "400";
    const range = pick("unicode-range");
    const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!src) continue;

    const bytes = Buffer.from(await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer());
    const hash = createHash("sha256").update(bytes).digest("hex");

    let name = byHash.get(hash);
    if (!name) {
      name = [slug(family), slug(weight), style, subset].join("-") + ".woff2";
      await writeFile(resolve(OUT, name), bytes);
      byHash.set(hash, name);
      console.log(`${name}  ${(bytes.length / 1024).toFixed(1)}kB`);
    }

    out.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${name}') format('woff2');\n` +
        `  unicode-range: ${range};\n` +
        `}`
    );
  }

  await writeFile(
    resolve(OUT, "fonts.css"),
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${out.join("\n\n")}\n`
  );
  console.log(`\n${out.length} faces over ${byHash.size} files → public/fonts/fonts.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
